version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed/tsed-mem-leak:latest
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true  # -i
    tty: true         # -t

